#  menu items
[[main]]
  name = "ğŸƒ Get started"
  weight = 1
  url = "book/get_started/"

[[main]]
  name = "ğŸ“– Book"
  weight = 2
  url = "book/"

[[main]]
  name = "â„¹ï¸ About"
  weight = 3
  url = "about/"