#  menu items
[[main]]
  name = "ğŸƒ Get started"
  weight = 1
  url = "documentation/get_started/"

[[main]]
  name = "ğŸ“– Documentation"
  weight = 2
  url = "documentation/"

[[main]]
  name = "â„¹ï¸ About"
  weight = 3
  url = "about/"